// =======================================================================
//                        !!! DO NOT EDIT THIS FILE !!!
// =======================================================================
//
// (c) 2021, Pavol Federl, pfederl@ucalgary.ca
// Do not distribute this file.

#pragma once
#include <vector>

std::vector<long> fat_check(const std::vector<long> & fat);
